name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js for Semantic Release
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install semantic-release globally
              run: |
                  npm install -g \
                    semantic-release \
                    @semantic-release/changelog \
                    @semantic-release/git \
                    @semantic-release/exec \
                    @semantic-release/github \
                    conventional-changelog-conventionalcommits

            - name: Run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

            - name: Upload version.txt artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-version
                  path: version.txt
